### ISSUE TITLE
Can only call submit function inside first get .done block

### ISSUE THREAD

**Issue by robertschank** [den-materials/js-ajax-lab#1]
http://stackoverflow.com/questions/29705626/run-function-inside-of-another-function-but-only-after-ajax-has-finished

http://stackoverflow.com/questions/3963906/problems-executing-a-jquery-ajax-call-within-a-function

jess's works with seemingly identical code

**Comment by ZebGirouard** [comment]
I believe this happened because of karma.  Please check your karma, and try again.
